export const GET_ALL_MEALS_FAILED = "GET_ALL_MEALS_FAILED";
export const CREATING_MEAL_FAILED = "CREATING_MEAL_FAILED";
export const NO_MATCH_BY_USER_ID = "NO_MATCH_BY_USER_ID";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const INVALID_ROUTE = "INVALID_ROUTE";
export const UNKNOWN_ERROR = "UNKNOWN_ERROR";
export const DATABASE_CONNECTION_FAILED = "Could not connect to database.";
export const GET_USER_BY_ID_FAILED = "GET_USER_BY_ID_FAILED";
export const COULD_NOT_FIND_MATCH_BY_PROVIDED_MEAL_ID =
  "COULD_NOT_FIND_MATCH_BY_PROVIDED_MEAL_ID";
export const DELETE_MEAL_FAILED = "DELETE_MEAL_FAILED";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const DELETE_MEAL_SUCCESS = "Successfully deleted meal.";
export const INVALID_INPUT = "INVALID_INPUT";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SIGNUP_FAILED_TOKEN_GENERATION = "SIGNUP_FAILED_TOKEN_GENERATION";
export const CREATING_USER_FAILED = "CREATING_USER_FAILED";
export const COULD_NOT_FIND_MATCH_BY_PROVIDED_USER_ID =
  "COULD_NOT_FIND_MATCH_BY_PROVIDED_USER_ID";
export const GET_ALL_MEALS_BY_USER_FAILED = "GET_ALL_MEALS_BY_USER_FAILED";
export const GET_MEAL_BY_ID_FAILED = "GET_MEAL_BY_ID_FAILED";
export const GET_USER_FAILED = "GET_USER_FAILED";
